name: 🤖 Auto Merge

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || contains(github.event.pull_request.labels.*.name, 'auto-merge')

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v4

      - name: ⏳ Wait for CI
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Code Quality"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: ⏳ Wait for Tests
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Tests"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: ✅ Auto approve
        if: github.actor == 'dependabot[bot]'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔀 Auto merge
        uses: pascalgn/merge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_commit_message: pull-request-title
          merge_filter_author: dependabot[bot]
