name: 📚 Sync Wiki

on:
  push:
    branches: [main]
    paths:
      - ".github/wiki/**"
  workflow_dispatch:

jobs:
  sync-wiki:
    name: Sync GitHub Wiki
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: 📚 Install dependencies
        run: npm ci

      - name: 🔄 Sync wiki content
        run: node scripts/sync-wiki.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💬 Comment on commit
        if: github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const sha = context.sha;

            await github.rest.repos.createCommitComment({
              owner,
              repo,
              commit_sha: sha,
              body: `📚 **Wiki Sync Completed!**\n\nYour wiki has been automatically updated with the latest changes.\n\n🔗 **Links:**\n- 📖 [View Wiki](https://github.com/${owner}/${repo}/wiki)\n- 📋 [Wiki Repository](https://github.com/${owner}/${repo}.wiki.git)\n\n*This comment was automatically generated by the Wiki Sync workflow.*`
            });
